### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by minichameleon** [ETCartman/Class_Npels#5]
我在调整间隔时间时试了很多数字，一段时间后都会报错，作者设置的间隔是多少呢？
另外是否可以检测到单词弹窗，然后定位到单词弹窗的确认按钮，进行下一步操作呢？

**Comment by badbubble** [comment]
时间间隔是60秒，毕竟大一时候写的程序 很多东西都没考虑到，好像确实时会报错..... 前几天有个同学用的也是隔一段时间就会报错....  因为老师说这个英语平台不会再使用了所以我就没看，确实也没有时间....

**Comment by minichameleon** [comment]
我尝试在 左右选项卡的时候 出错时（应该是出现单词卡）抛出异常，使用self.driver.find_element_by_xpath(
                    "// *[ @ id = 'frameless'] / div[1] / div / input[@type='button'and @value='我记住了'] ").click()，来定位我记住了这个按钮，但是还是会报错，是我这定位写的不太对？

**Comment by badbubble** [comment]
什么错误，是找不到位置吗 ？  应该是弹出窗口在不同的frame中，你可以找找弹出窗口所在的Frame https://blog.csdn.net/huilan_same/article/details/52200586
