### ISSUE TITLE
这是怎么了

### ISSUE THREAD

**Issue by Innei** [ETCartman/Class_Npels#6]
![image](https://user-images.githubusercontent.com/41265413/45750384-6482f400-bc41-11e8-93a7-9eca63e5490b.png)

**Comment by Innei** [comment]
![image](https://user-images.githubusercontent.com/41265413/45750899-17078680-bc43-11e8-9190-e6d2ebc0d19c.png)

**Comment by badbubble** [comment]
8102年了 兄弟，咋还在用这个脚本..... 应该是Chrome的驱动器太老了 你换一个最新的试试

**Comment by Innei** [comment]
![image](https://user-images.githubusercontent.com/41265413/45799889-a4011d00-bce1-11e8-9883-2ef6aa285b19.png)
更新了驱动之后还是不行

**Comment by badbubble** [comment]
您把Chromedriver.exe放在哪个文件夹下面？

**Comment by Innei** [comment]
python安装根目录

**Comment by badbubble** [comment]
你把它和run.py放在一个目录试试

**Comment by Innei** [comment]
好的 晚上试试

**Comment by badbubble** [comment]
ok

**Comment by Innei** [comment]
冒昧的问一下 这个支持win吗 mac可以吗

**Comment by badbubble** [comment]
[mac chromedriver](https://chromedriver.storage.googleapis.com/2.42/chromedriver_mac64.zip) 你可以试试

**Comment by Innei** [comment]
![image](https://user-images.githubusercontent.com/41265413/45818446-5ce04f80-bd14-11e8-83a0-ed1d9b871933.png)
这是怎么回事..

**Comment by badbubble** [comment]
咦。。。 网页更新了？我同学上学期挂还没问题

**Comment by Innei** [comment]
卡在选课的地方 .版本是V6.2

**Comment by badbubble** [comment]
你看看 原理请简单的 就是找到指定标签然后点击。。。。 我估计最近没时间改这个程序 你可以先用一下鼠标连点器是一样的
